dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
os:
  - osx
  # - linux
# addons:
#   apt:
#     packages:
#     - rpm
script:
  - echo "No tests"
deploy:
  provider: script
  skip_cleanup: true
  script: yarn run publish
  on:
    tags: true
